### ISSUE TITLE
problem: unhandled promise rejection 

### ISSUE THREAD

**Issue by gazhayes** [zulip/zulipbot#160]
Problem: there's an unhandled promise rejection. 

Am I doing something wrong?
```
An unhandled promise rejection was detected at: Promise {
  <rejected> TypeError: Cannot read property 'id' of undefined
    at module.exports.exports.progress (/home/gareth/emurgobot/src/automations/issueState.js:47:51)
    at module.exports.exports.run (/home/gareth/emurgobot/src/events/issue.js:8:40)
    at app.post (/home/gareth/emurgobot/src/index.js:30:23)
    at Layer.handle [as handle_request] (/home/gareth/emurgobot/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/gareth/emurgobot/node_modules/express/lib/router/route.js:137:13)
    at /home/gareth/emurgobot/node_modules/body-parser/lib/read.js:130:5
    at invokeCallback (/home/gareth/emurgobot/node_modules/raw-body/index.js:224:16)
    at done (/home/gareth/emurgobot/node_modules/raw-body/index.js:213:7)
    at IncomingMessage.onEnd (/home/gareth/emurgobot/node_modules/raw-body/index.js:273:7)
    at emitNone (events.js:106:13) }
An unhandled promise rejection was detected at: Promise {
  <rejected> TypeError: Cannot read property 'id' of undefined
    at module.exports.exports.progress (/home/gareth/emurgobot/src/automations/issueState.js:47:51)
    at module.exports.exports.run (/home/gareth/emurgobot/src/events/issue.js:8:40)
    at app.post (/home/gareth/emurgobot/src/index.js:30:23)
    at Layer.handle [as handle_request] (/home/gareth/emurgobot/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/gareth/emurgobot/node_modules/express/lib/router/route.js:137:13)
    at /home/gareth/emurgobot/node_modules/body-parser/lib/read.js:130:5
    at invokeCallback (/home/gareth/emurgobot/node_modules/raw-body/index.js:224:16)
    at done (/home/gareth/emurgobot/node_modules/raw-body/index.js:213:7)
    at IncomingMessage.onEnd (/home/gareth/emurgobot/node_modules/raw-body/index.js:273:7)
    at emitNone (events.js:106:13) }
An unhandled promise rejection was detected at: Promise {
  <rejected> TypeError: Cannot read property 'id' of undefined
    at module.exports.exports.progress (/home/gareth/emurgobot/src/automations/issueState.js:47:51)
    at module.exports.exports.run (/home/gareth/emurgobot/src/events/issue.js:8:40)
    at app.post (/home/gareth/emurgobot/src/index.js:30:23)
    at Layer.handle [as handle_request] (/home/gareth/emurgobot/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/gareth/emurgobot/node_modules/express/lib/router/route.js:137:13)
    at /home/gareth/emurgobot/node_modules/body-parser/lib/read.js:130:5
    at invokeCallback (/home/gareth/emurgobot/node_modules/raw-body/index.js:224:16)
    at done (/home/gareth/emurgobot/node_modules/raw-body/index.js:213:7)
    at IncomingMessage.onEnd (/home/gareth/emurgobot/node_modules/raw-body/index.js:273:7)
    at emitNone (events.js:106:13) }
An unhandled promise rejection was detected at: Promise {
  <rejected> TypeError: Cannot read property 'id' of undefined
    at module.exports.exports.progress (/home/gareth/emurgobot/src/automations/issueState.js:47:51)
    at module.exports.exports.run (/home/gareth/emurgobot/src/events/issue.js:8:40)
    at app.post (/home/gareth/emurgobot/src/index.js:30:23)
    at Layer.handle [as handle_request] (/home/gareth/emurgobot/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/gareth/emurgobot/node_modules/express/lib/router/route.js:137:13)
    at /home/gareth/emurgobot/node_modules/body-parser/lib/read.js:130:5
    at invokeCallback (/home/gareth/emurgobot/node_modules/raw-body/index.js:224:16)
    at done (/home/gareth/emurgobot/node_modules/raw-body/index.js:213:7)
    at IncomingMessage.onEnd (/home/gareth/emurgobot/node_modules/raw-body/index.js:273:7)
    at emitNone (events.js:106:13) }
An unhandled promise rejection was detected at: Promise {
  <rejected> TypeError: Cannot read property 'id' of undefined
    at module.exports.exports.progress (/home/gareth/emurgobot/src/automations/issueState.js:47:51)
    at module.exports.exports.run (/home/gareth/emurgobot/src/events/issue.js:8:40)
    at app.post (/home/gareth/emurgobot/src/index.js:30:23)
    at Layer.handle [as handle_request] (/home/gareth/emurgobot/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/gareth/emurgobot/node_modules/express/lib/router/route.js:137:13)
    at /home/gareth/emurgobot/node_modules/body-parser/lib/read.js:130:5
    at invokeCallback (/home/gareth/emurgobot/node_modules/raw-body/index.js:224:16)
    at done (/home/gareth/emurgobot/node_modules/raw-body/index.js:213:7)
    at IncomingMessage.onEnd (/home/gareth/emurgobot/node_modules/raw-body/index.js:273:7)
    at emitNone (events.js:106:13) }
An unhandled promise rejection was detected at: Promise {
  <rejected> TypeError: Cannot read property 'id' of undefined
    at module.exports.exports.progress (/home/gareth/emurgobot/src/automations/issueState.js:47:51)
    at module.exports.exports.run (/home/gareth/emurgobot/src/events/issue.js:8:40)
    at app.post (/home/gareth/emurgobot/src/index.js:30:23)
    at Layer.handle [as handle_request] (/home/gareth/emurgobot/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/gareth/emurgobot/node_modules/express/lib/router/route.js:137:13)
    at /home/gareth/emurgobot/node_modules/body-parser/lib/read.js:130:5
    at invokeCallback (/home/gareth/emurgobot/node_modules/raw-body/index.js:224:16)
    at done (/home/gareth/emurgobot/node_modules/raw-body/index.js:213:7)
    at IncomingMessage.onEnd (/home/gareth/emurgobot/node_modules/raw-body/index.js:273:7)
    at emitNone (events.js:106:13) }
```

**Comment by gazhayes** [comment]
Fixed here in case anyone else is having this issue: https://github.com/EmurgoHK/emurgobot/pull/3

**Comment by lonerz** [comment]
Thanks! @synicalsyntax can you check out the PR and maybe merge our own copy?

**Comment by synicalsyntax** [comment]
@gazhayes Just curious; are you using GitHub webhooks to deliver your payloads? We can't reproduce those errors with the zulipbot payloads delivered through Github Apps.

**Comment by gazhayes** [comment]
Yeah we're using webhooks. Hmmmm, @anbud might be able to help here.

**Comment by synicalsyntax** [comment]
I'll look into seeing if I can reproduce through webhooks, thanks for the info :)

**Comment by anbud** [comment]
The problem was [here](https://github.com/EmurgoHK/emurgobot/pull/3/files#diff-380c87cd68b27db98ce4ac031a403ebbR47), `payload.assignee` was always undefined, as there's no `assignee` field in the payload. But, there's an `assignee` field in `payload.issue` which is either null or the actual asignee. So, changing that line fixed the issue.

**Comment by synicalsyntax** [comment]
@anbud In my repository's webhooks, `payload.assignee` is always present. For example:

```json
{
  "action": "assigned",
  "assignee": {
    "login": "synicalsyntax",
    "id": 15116870,
    "node_id": "MDQ6VXNlcjE1MTE2ODcw",
    "avatar_url": "https://avatars0.githubusercontent.com/u/15116870?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/synicalsyntax",
    "html_url": "https://github.com/synicalsyntax",
    "followers_url": "https://api.github.com/users/synicalsyntax/followers",
    "following_url": "https://api.github.com/users/synicalsyntax/following{/other_user}",
    "gists_url": "https://api.github.com/users/synicalsyntax/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/synicalsyntax/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/synicalsyntax/subscriptions",
    "organizations_url": "https://api.github.com/users/synicalsyntax/orgs",
    "repos_url": "https://api.github.com/users/synicalsyntax/repos",
    "events_url": "https://api.github.com/users/synicalsyntax/events{/privacy}",
    "received_events_url": "https://api.github.com/users/synicalsyntax/received_events",
    "type": "User",
    "site_admin": false
  }
}
```

I have no idea why your webhook payloads don't contain the `assignee` field; all my webhook payloads contain them :\ I'm not sure if it's a bug in the GitHub API or something else.

Can you send me the content of a webhook payload with the `action` field specified with a "assigned" value?

Also, even though it's not really related to misconstructed webhook payloads, it might help if you try rebasing your fork onto the latest master branch so that we're on the same page :)

**Comment by synicalsyntax** [comment]
Also, regarding `payload.issue.assignee`: its value is always set to the first user that the issue was assigned to, and it still persists when someone is assigned and there are no more assignees on the issue, so it isn't the best solution. The only reason we're checking the assignee's in the first place is because of a GitHub API bug that breaks the `in progress` label removal whenever there's no more assignees on an issue.

**Comment by gazhayes** [comment]
weird, @anbud could it be anything specific to our repos or deployment?

**Comment by anbud** [comment]
I've just browsed through old webhook logs and the thing is, it wasn't raising this exception when the `action` field was `assigned`, it broke when the `action` field was `created` or something similar. 

For example, here are a few payloads which caused this exception and 500 response: [example1](https://ybin.me/p/3cf7f4ecb799f721#eeiXvdwPLEGpDKSei5B4Oah3P2T1byTTCngujClpszM=), [example2](https://ybin.me/p/adca31a378515f16#Fp5n2M0yU19DeQRgZShrS8tKo5bu0r6JpLoNo32sO0c=), [example3](https://ybin.me/p/6b28633fe9b0596c#z1vDewaD4rZXyj1opMxr3i4+APfHMi/KnIX5rNUN+Gc=). For all three examples, headers are something like this:
```
Request URL: http://58.152.37.119:3333/github
Request method: POST
content-type: application/json
Expect: 
User-Agent: GitHub-Hookshot/c8ef286
X-GitHub-Delivery: 6d9e6f30-b352-11e8-8ef0-a1ccc00f3a63
X-GitHub-Event: issue_comment
X-Hub-Signature: sha1=4c075ea4fc9a70246365e1b524b60bec8fe28840
```
with different signatures, of course.

I can't seem to find any logs where the `action` field was `assigned`. Maybe that's the main issue here. 

Could it be a misconfiguration on our side? Webhooks are set to deliver everything to the zulipbot endpoint, and I believe I've followed the README to the point when setting it up.

About the `payload.issue.assignee` field, that's the closest one I saw in the payload and I just assumed it's the same thing as `payload.assignee`. But you're right, it isn't the best solution here then. Although, after this patch, we didn't have any issues whatsoever with zulipbot. I'll rebase our fork soon, it would definitely help to be on the same page.

Please let me know if I can provide more info about this, or if you need anything else. 
Thank you! :)

**Comment by synicalsyntax** [comment]
@anbud Ah, issue makes more sense now. So it looks like on your commit, we're just calling the in progress label switch regardless of the issue payload action, which results in assignee sometimes being undefined. If you upgrade to the most recent commit, this issue should be resolved. (It also seems like we faced this assignee issue early on; the specific commit that fixes it is 9be4a7f98e). Please let me know if you have any issues upgrading or if you need help with anything else! :)
